remote_theme: mmistakes/minimal-mistakes@latest
title: My Jekyll Site
description: A simple Jekyll-powered site.
url: https://your-username.github.io

navigation:
  - name: Home
    link: /
  - name: CFD
    link: /blog
